const KEYWORDS = {
    HIFADHI: "hifadhi",
    WAKATI: "wakati",
    ANDIKA: "andika",
    BASI: "basi",
    KWELI: "kweli",
    SIKWELI: "sikweli",
    NJIA: "njia",
    HAKIKA: "hakika",
    REJESHA: "rejesha",
    VUNJA: "vunja",
    KAMA: "kama",
    CHAGUA: "chagua",
    KESI: "kesi",
    ZAIDI: "zaidi",
    LETE: "lete",
    ITA: "ita",
    JARIBU: "jaribu",
    KAMATA: "kamata",
    RAMANI: "ramani",
};

const SYMBOLS = {
    STR_QUOTE: '"',
    PERIOD: ".",
    OR: "||",
    AND: "&&",
    BINARY_AND: "&",
    L_THAN: "<",
    G_THAN: ">",
    G_THAN_OR_EQ: ">=",
    L_THAN_OR_EQ: "<=",
    NOT_EQ: "!=",
    EQ: "==",
    ASSIGN: "=",
    PLUS: "+",
    MINUS: "-",
    MULTIPLY: "*",
    DIVIDE: "/",
    REMAINDER: "%",
    L_PAREN: "{",
    R_PAREN: "}",
    COMMA: ",",
    COMMENT: "#",
    L_BRACKET: "(",
    R_BRACKET: ")",
    L_SQ_BRACKET: "[",
    R_SQ_BRACKET: "]",
    STATEMENT_TERMINATOR: ";",
    NEW_LINE: "\n",
    TAB_SPACE: "\t",
    EMPTY_SPACE: " ",
    EXCLAMATION_POINT: "!",
    PIPE: "|",
    COLON: ":",
    BACK_TICK: "`",
};

const LIST = {
    PUNCTUATIONS: [
        SYMBOLS.L_BRACKET, SYMBOLS.R_BRACKET, SYMBOLS.L_PAREN,
        SYMBOLS.R_PAREN, SYMBOLS.STATEMENT_TERMINATOR, SYMBOLS.COMMA,
        SYMBOLS.L_SQ_BRACKET, SYMBOLS.R_SQ_BRACKET, SYMBOLS.COLON, SYMBOLS.BACK_TICK,
        SYMBOLS.PERIOD,
    ],
    OPERATORS: [
        SYMBOLS.PLUS, SYMBOLS.MINUS, SYMBOLS.MULTIPLY,
        SYMBOLS.DIVIDE, SYMBOLS.REMAINDER, SYMBOLS.L_THAN,
        SYMBOLS.G_THAN, SYMBOLS.EQ, SYMBOLS.EXCLAMATION_POINT,
        SYMBOLS.PIPE, SYMBOLS.BINARY_AND, SYMBOLS.ASSIGN,
    ],
    WHITESPACES: [
        SYMBOLS.EMPTY_SPACE, SYMBOLS.TAB_SPACE, SYMBOLS.NEW_LINE,
    ],
    KEYWORDS: [
        KEYWORDS.HIFADHI, KEYWORDS.WAKATI, KEYWORDS.KAMA, KEYWORDS.ANDIKA,
        KEYWORDS.BASI, KEYWORDS.KWELI, KEYWORDS.SIKWELI, KEYWORDS.NJIA,
        KEYWORDS.HAKIKA, KEYWORDS.REJESHA, KEYWORDS.VUNJA, KEYWORDS.CHAGUA,
        KEYWORDS.KESI, KEYWORDS.ZAIDI, KEYWORDS.LETE, KEYWORDS.ITA,
        KEYWORDS.JARIBU, KEYWORDS.KAMATA, KEYWORDS.RAMANI,
    ],
};

const REGEX = {
    DIGIT: /[0-9]/i,
    IDENTIFIER: /[a-zA-Z]|[ÁÀÉÈẸẸ́Ẹ̀ẸĒÍÌÓÒỌỌ́Ọ̀ỌÚÙṢáàéèẹẹ́ẹíìóòọọ́ọ̀úùṣŃń]/i,
};

const constants = {
    KW: KEYWORDS,
    SYM: SYMBOLS,
    LIST: LIST,
    REGEX: REGEX,
    KEYWORD: "keyword",
    VARIABLE: "variable",
    STRING: "string",
    ARRAY: "array",
    ARRAY_ELEM: "arrayElement",
    MAP: "map",
    MAP_ELEM: "mapElement",
    LAMBDA: "lambda",
    NUMBER: "number",
    PROGRAM: "program",
    PUNCTUATION: "punctuation",
    OPERATOR: "operator",
    GET_HIFADHI: "getHifadhi",
    CALL_KAZI: "callKazi",
    EXP_PUNC: "expression_punctuations",
    SWAP_EXT: ".sw",
    NEGATE_EXPRESSION: "negate_exp",
};

module.exports = constants;
